services:
  backend-ingestor:
    build:
      context: ./backend-ingestor
      dockerfile: Dockerfile
    container_name: geosync_engine
    volumes:
      - ./backend-ingestor:/app
      - ./backend-ingestor/data:/app/data
    env_file:
      - ./backend-ingestor/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - geosync-network

networks:
  geosync-network:
    driver: bridge
